### ISSUE TITLE
Add support for querying medications without dm+d codes in TPP

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/ehrql#1270]
In TPP, medications in the `MedicationIssue` table are recorded with Multilex codes.  The `MedicationDictionary` table maps from Multilex to dm+d codes, allowing users to look up medication events with a dm+d codelist.

Some medication events have Multilex codes that do not have a mapping to a dm+d code.  Our clinical informatics team have investigated this and in most cases this is not a problem.  However, there are some Multiliex codes whose mapping to a dm+d code is missing from `MedicationDictionary`.  In particular, a significant number of morphine prescriptions do not have dm+d codes, and so are missed.  See discussion at https://github.com/ebmdatalab/sensitive-issues/issues/15.

In some cases the `MedicationDictionary` may be updated (eventually) but this is not guaranteed, so we need to be able to use our own mappings (provided by the clinical informatics team).  The mappings can be stored in a CSV file in this repo.

We should ensure that duplicates between our own mapping and the mapping in `MedicationDictionary` do not result in double counting medication events, and we should prefer mappings from `MedicationDictionary`.  If this is hard to do efficiently on each query, we should consider some other way of checking that there are no duplicates.

Acceptance criteria:

- [x] A test dataset definition using the [morphine-subcutaneous-dmd codelist](https://www.opencodelists.org/codelist/opensafely/morphine-subcutaneous-dmd/1185fc5b/) captures more events after this fix is deployed than before it is deployed.

**Comment by evansd** [comment]
At one level, I think this is fairly simple. It's a case of changing the QueryTable definition from:
https://github.com/opensafely-core/ehrql/blob/06c19588d14f5f5aa2d821239f6d9e2d0b2ddbe6/ehrql/backends/tpp.py#L98-L109

To something which includes an extra join on `OurCustomDictionary` (but prefers results from `MedicationDictionary` where they exist):
```sql
SELECT
    meds.Patient_ID AS patient_id,
    CAST(meds.ConsultationDate AS date) AS date,
    COALESCE(dict.DMD_ID, our_dict.DMD_ID) AS dmd_code,
    meds.MultilexDrug_ID AS multilex_code
FROM MedicationIssue AS meds
LEFT JOIN MedicationDictionary AS dict
ON meds.MultilexDrug_ID = dict.MultilexDrug_ID
LEFT JOIN OurCustomDictionary AS our_dict
ON meds.MultilexDrug_ID = our_dict.MultilexDrug_ID
```

The question is how the `OurCustomDictionary` table gets created and maintained. There are two different ways we could go here.

 1. One is to manage the table externally to this repo i.e. have some script or service which runs on TPP which creates and populates the table. I remember discussing similar plans in the context of codelist rot. In fact, is it possible we [already do this](https://github.com/opensafely-core/cohort-extractor/pull/896) with a `VmpMapping` table?

    This is conceptually the neatest approach as it gives us a clean separation between ehrQL and the data and ehrQL itself doesn't have to care whether a given table is maintained by TPP or by us.

    Whether it's a good idea overall depends, I think, on whether we're going to need this kind of table-maintaining machinery for other purposes anyway. If we _are_ then it makes sense to use it for this purpose too.

 2. The other option is to have ehrQL manage the table. This is conceptually, and code-wise, more messy but it doesn't require an additional moving part. If we went down this route we'd want to use a session-scoped temporary table which create each time we need it, rather than trying to do anything stateful.

    We already have the `GeneratedTable` mechanism for managing the lifecycle of temporary tables. So we'd need to fiddle around with the TPP backend (and possibly the backend API more generally) so that the `medications` table carries with it the queries needed to create and populate our custom dictionary.

**Comment by iaindillingham** [comment]
Thanks for your comment, @evansd, it really helped me understand the issue.

We do have a `VmpMapping` table, which is in a temporary database. It's created by cohort-extractor's `update_vmp_mapping` subcommand, which calls the OpenCodelists API through a proxy. I don't know who calls this subcommand and how frequently they call it (Becky?). However, this approach would provide a clean separation between the data and ehrQL, as you say.

Whilst we could, for the moment, commit a CSV of mappings to this repo, and add a subcommand to create a temporary table and insert the mappings into it, we're not tied to this implementation.

The second option -- ehrQL manages the table -- does indeed seem messy by comparison. I think we'd add a method to `BaseSQLQueryEngine` that would return a `GeneratedTable`; similar to how `BaseSQLQueryEngine.get_table_inline_patient_table` does now. My first thought was, "What's the performance penalty of reading, creating, and inserting each time?" but on reflection, I think my second thought, which was "That's really fiddly", is more germane.

I'm afraid that I don't know whether we're going to need to do this kind of thing more often. However, in my naivety, I think we might: we don't have a `SNOMEDCT` table that maps from SNOMEDCT codes to CTV3 codes. Would this not be useful? (I could have used it during recent work on OpenPROMPT, for example.) Setting that aside, the first option seems to me to be more tractable than the second option.

**Comment by iaindillingham** [comment]
- [ ] Update cohort-extractor opensafely-core/cohort-extractor#961
- [ ] Create the table in the temporary database
- [ ] Update ehrQL opensafely-core/ehrql#1348
- [ ] Ask the clinical informatics team to check the test dataset definition opensafely/custom-medication-dictionary-test#2
- [ ] Run the before test
- [ ] Add the missing codes to [the CSV file](https://github.com/opensafely-core/cohort-extractor/blob/main/cohortextractor/custom_medication_dictionary.csv)
- [ ] Run the after test

**Comment by iaindillingham** [comment]
The [test dataset definition](https://github.com/opensafely/custom-medication-dictionary-test/blob/main/analysis/dataset_definition.py) captures roughly 16 times more events after the fix than before the fix for the medications given in [the custom medication dictionary](https://github.com/opensafely-core/cohort-extractor/blob/main/cohortextractor/custom_medication_dictionary.csv).
