### ISSUE TITLE
Write release notes for ehrQL v1

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/ehrql#1764]
These should describe the major changes for users moving from v0 to v1.

This probably should go in the ehrQL documentation.

Below are items that could be mentioned in these notes. Some of the items listed below are major changes that have happened in recent development for the ["deprecate cohort-extractor" milestone](https://github.com/opensafely-core/ehrql/milestone/2), and not just the breaking changes for v1.

It's debatable what might go into these notes, aside from breaking changes that will mark v1. It's trickier to write a more general changelog for v1, because that's been the entirety of development. This might be much simpler for an ehrQL v2. 

## General changes

- [x] the name change from Data Builder to ehrQL
- [x] direct import of `Dataset`; favour `create_dataset` (#1599)
- [x] disclosure control for measures (#1746)

## Breaking changes

- [x] deprecation of the `databuilder` Docker image; use `ehrql` (#1765)
  * do we need to suggest that the Data Builder image should be manually removal by users, via `docker rm` ? (it's not massive, but is possibly something like 0.5 GB of storage just sat there that will never get removed)
- [x] use of `ehrql:v1` in `project.yaml` instead of `ehrql:v0`
- [x] removal of `databuilder` imports; use `ehrql` imports (#1221)
- [x] use of raw tables (#1705); these are moved into the `raw` namespace
- [x] deprecation of `tpp.hospital_admissions.primary_diagnoses` (#1743); use `tpp.hospital_admissions.primary_diagnosis` (may be moot if `hospital_admissions` is consolidated with `apcs`)
- [x] possible consolidation of `apcs` and `hospital_admissions` (#1761)

(feel free to update)
